/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:867302:
  appc.background(230);
} //_CODE_:window1:867302:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:610620:
  ui = new UiState();
} //_CODE_:resetButton:610620:

public void saveButtonClicked(GButton source, GEvent event) { //_CODE_:saveButton:610189:
  selectInput("Pick a file to save data to:", "saveUiJSON");
} //_CODE_:saveButton:610189:

public void loadButtonClicked(GButton source, GEvent event) { //_CODE_:loadButton:309090:
  selectInput("Load a JSON file:", "loadUiJSON");
} //_CODE_:loadButton:309090:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 150, 140, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  resetButton = new GButton(window1, 35, 10, 80, 30);
  resetButton.setText("Reset");
  resetButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  resetButton.addEventHandler(this, "resetButtonClicked");
  saveButton = new GButton(window1, 35, 50, 80, 30);
  saveButton.setText("Save");
  saveButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  saveButton.addEventHandler(this, "saveButtonClicked");
  loadButton = new GButton(window1, 35, 90, 80, 30);
  loadButton.setText("Load");
  loadButton.addEventHandler(this, "loadButtonClicked");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton resetButton; 
GButton saveButton; 
GButton loadButton; 
